const http=require('http');const fs=require('fs');const path=require('path');const crypto=require('crypto');const {spawn}=require('child_process');const QR=require('qrcode');
const PORT=Number(process.env.PORT||1323),GATEWAY_PORT=Number(process.env.GATEWAY_PORT||1400),XRAY_DEFAULT_PORT=Number(process.env.XRAY_DEFAULT_PORT||15001),ROOT=__dirname,PUBLIC=path.join(ROOT,'public'),DATA=path.join(ROOT,'data');
const NGINX_BIN=process.env.NGINX_BIN||'/usr/sbin/nginx',NGINX_CFG=path.join(DATA,'nginx.conf'),NGINX_PID=path.join(DATA,'nginx.pid'),INTERNAL_BASE=Number(process.env.XRAY_INTERNAL_BASE||20000);
let nginxProc=null;
const DB=path.join(DATA,'panel.json'),XRAY_BIN=process.env.XRAY_BIN||'/usr/local/bin/xray',XRAY_CFG=path.join(DATA,'xray-runtime.json');
let xrayProc=null,xrayLog=[],sessions=new Map();
const hash=p=>crypto.createHash('sha256').update(String(p)).digest('hex');
function init(){fs.mkdirSync(DATA,{recursive:true});let d;if(fs.existsSync(DB)){try{d=JSON.parse(fs.readFileSync(DB,'utf8'))}catch{d=null}}if(!d)d={configs:[],inbounds:[],settings:{subscriptionBase:process.env.PUBLIC_BASE_URL||'',subscriptionPath:'/sub/'},auth:{username:'admin',passwordHash:hash('admin')}};if(!d.auth)d.auth={username:'admin',passwordHash:hash('admin')};if(!d.settings)d.settings={};if(!d.settings.subscriptionBase)d.settings.subscriptionBase=process.env.PUBLIC_BASE_URL||((process.env.RAILWAY_PUBLIC_DOMAIN)?'https://'+process.env.RAILWAY_PUBLIC_DOMAIN:'');d.settings.gatewayPort=GATEWAY_PORT;d.settings.defaultPublicPort=443;saveDB(d)}
function saveDB(v){fs.writeFileSync(DB,JSON.stringify(v,null,2))}function db(){try{return JSON.parse(fs.readFileSync(DB,'utf8'))}catch{return {configs:[],inbounds:[],settings:{},auth:{username:'admin',passwordHash:hash('admin')}}}}
function json(res,c,d,extra={}){res.writeHead(c,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...extra});res.end(JSON.stringify(d))}
function readBody(req){return new Promise((ok,bad)=>{let s='';req.on('data',c=>{s+=c;if(s.length>10e6)req.destroy()});req.on('end',()=>{try{ok(s?JSON.parse(s):{})}catch(e){bad(e)}});req.on('error',bad)})}
function cookies(req){const out={};for(const x of (req.headers.cookie||'').split(';')){const i=x.indexOf('=');if(i>0)out[x.slice(0,i).trim()]=decodeURIComponent(x.slice(i+1).trim())}return out}
function auth(req){const t=cookies(req).xray_session;return !!(t&&sessions.has(t))}
function need(req,res){if(auth(req))return true;json(res,401,{error:'Unauthorized'});return false}
function id(){return crypto.randomUUID()}
const MIME={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.json':'application/json; charset=utf-8','.svg':'image/svg+xml'};
function validate(c){const e=[];if(!['vless','vmess','trojan','shadowsocks'].includes(c.protocol))e.push('protocol');if(!['tcp','ws','grpc','httpupgrade','xhttp','http'].includes(c.transport))e.push('transport');if(!['none','tls','reality'].includes(c.security))e.push('security');if(!c.server?.address)e.push('server.address');if(!(Number(c.server?.port)>0&&Number(c.server.port)<65536))e.push('server.port');if(['vless','vmess'].includes(c.protocol)&&!c.identity?.uuid)e.push('uuid');if(['trojan','shadowsocks'].includes(c.protocol)&&!c.identity?.password)e.push('password');if(c.security==='tls'&&!c.tls?.serverName)e.push('tls.serverName');if(c.security==='reality'&&(!c.reality?.serverName||!c.reality?.publicKey||!c.reality?.shortId))e.push('reality serverName/publicKey/shortId');if(c.transport==='ws'&&!c.transportOptions?.path)e.push('ws path');if(c.transport==='grpc'&&!c.transportOptions?.serviceName)e.push('grpc serviceName');if(c.transport==='xhttp'&&!c.transportOptions?.path)e.push('xhttp path');return e}
function stream(c){let r={network:c.transport};if(c.security==='tls')r=Object.assign(r,{security:'tls',tlsSettings:{serverName:c.tls.serverName,alpn:c.tls.alpn||[],fingerprint:c.tls.fingerprint||'chrome',allowInsecure:!!c.tls.allowInsecure}});if(c.security==='reality')r=Object.assign(r,{security:'reality',realitySettings:{serverName:c.reality.serverName,publicKey:c.reality.publicKey,shortId:c.reality.shortId,fingerprint:c.reality.fingerprint||'chrome',spiderX:c.reality.spiderX||''}});const o=c.transportOptions||{};if(c.transport==='ws')r.wsSettings={path:o.path||'/',headers:o.host?{Host:o.host}:{} };if(c.transport==='grpc')r.grpcSettings={serviceName:o.serviceName||'',multiMode:!!o.multiMode,mode:o.mode||'gun'};if(c.transport==='httpupgrade')r.httpupgradeSettings={path:o.path||'/',host:o.host||''};if(c.transport==='xhttp')r.xhttpSettings={path:o.path||'/',host:o.host||'',mode:o.mode||'auto',extra:obj(o.extra)};if(c.transport==='http')r.httpSettings={path:o.path||'/',host:o.hosts||[]};return r}
function obj(v){if(!v)return undefined;try{return JSON.parse(v)}catch{return undefined}}
function outbound(c){let settings;if(c.protocol==='vless')settings={vnext:[{address:c.server.address,port:Number(c.server.port),users:[{id:c.identity.uuid,encryption:c.identity.encryption||'none',flow:c.identity.flow||''}]}]};if(c.protocol==='vmess')settings={vnext:[{address:c.server.address,port:Number(c.server.port),users:[{id:c.identity.uuid,alterId:Number(c.identity.alterId||0),security:c.identity.encryption||'auto'}]}]};if(c.protocol==='trojan')settings={servers:[{address:c.server.address,port:Number(c.server.port),password:c.identity.password,flow:c.identity.flow||''}]};if(c.protocol==='shadowsocks')settings={servers:[{address:c.server.address,port:Number(c.server.port),method:c.identity.method||'aes-128-gcm',password:c.identity.password}]};return {protocol:c.protocol,settings,streamSettings:stream(c),tag:c.meta?.tag||'proxy'}}
function uri(c){const o=c.transportOptions||{},q=new URLSearchParams({type:c.transport});if(c.security!=='none')q.set('security',c.security);if(c.security==='tls'){q.set('sni',c.tls.serverName);if(c.tls.fingerprint)q.set('fp',c.tls.fingerprint);if(c.tls.alpn?.length)q.set('alpn',c.tls.alpn.join(','))}if(c.security==='reality'){q.set('sni',c.reality.serverName);q.set('pbk',c.reality.publicKey);q.set('sid',c.reality.shortId);q.set('fp',c.reality.fingerprint||'chrome');if(c.reality.spiderX)q.set('spx',c.reality.spiderX)}if(['ws','xhttp','httpupgrade'].includes(c.transport)){q.set('path',o.path||'/');if(o.host)q.set('host',o.host)}if(c.transport==='grpc')q.set('serviceName',o.serviceName||'');const n=encodeURIComponent(c.meta?.name||'Xray');if(c.protocol==='vless'){q.set('encryption',c.identity.encryption||'none');if(c.identity.flow)q.set('flow',c.identity.flow);return `vless://${encodeURIComponent(c.identity.uuid)}@${c.server.address}:${c.server.port}?${q}#${n}`}if(c.protocol==='trojan')return `trojan://${encodeURIComponent(c.identity.password)}@${c.server.address}:${c.server.port}?${q}#${n}`;if(c.protocol==='vmess'){const x={v:'2',ps:c.meta?.name||'Xray',add:c.server.address,port:String(c.server.port),id:c.identity.uuid,aid:String(c.identity.alterId||0),scy:c.identity.encryption||'auto',net:c.transport,type:'none',host:o.host||'',path:o.path||'',tls:c.security==='tls'?'tls':c.security==='reality'?'reality':'',sni:c.security==='tls'?c.tls.serverName:c.security==='reality'?c.reality.serverName:''};return 'vmess://'+Buffer.from(JSON.stringify(x)).toString('base64')};if(c.protocol==='shadowsocks'){const u=Buffer.from(`${c.identity.method||'aes-128-gcm'}:${c.identity.password}`).toString('base64');return `ss://${u}@${c.server.address}:${c.server.port}?${q}#${n}`}}
function outputs(c){return {xray:{log:{loglevel:'warning'},outbounds:[outbound(c)]},uri:uri(c),summary:{protocol:c.protocol,transport:c.transport,security:c.security,address:c.server.address,port:Number(c.server.port),name:c.meta?.name||'Xray'}}}
function inboundToXray(i){const s=i.settings||{};const streamSettings=JSON.parse(JSON.stringify(s.streamSettings||{network:i.transport}));streamSettings.network=i.transport||streamSettings.network||'tcp';if(i.security==='tls'){streamSettings.security='tls';streamSettings.tlsSettings=i.tlsSettings||{serverName:i.sni||''}}else if(i.security==='reality'){streamSettings.security='reality';streamSettings.realitySettings=i.realitySettings||{}}else streamSettings.security='none';let settings={};if(i.protocol==='vless')settings={clients:(s.clients||[]).map(x=>({id:x.id,email:x.email||'',flow:x.flow||''})),decryption:'none'};if(i.protocol==='vmess')settings={clients:(s.clients||[]).map(x=>({id:x.id,alterId:Number(x.alterId||0),email:x.email||''}))};if(i.protocol==='trojan')settings={clients:(s.clients||[]).map(x=>({password:x.password,email:x.email||''}))};if(i.protocol==='shadowsocks')settings={method:s.method||'aes-128-gcm',password:s.password||'',network:s.network||'tcp,udp'};const httpish=new Set(['ws','xhttp','httpupgrade','http','grpc']);const listen=httpish.has(i.transport)?'127.0.0.1':(i.listen||'0.0.0.0');return {listen,port:Number(i.internalPort||i.port),protocol:i.protocol,settings,streamSettings,tag:i.tag||('in-'+i.protocol)} }
function validateInbounds(items){const e=[];const seenInternal=new Set(),pathSeen=new Set();const httpish=new Set(['ws','xhttp','httpupgrade','http','grpc']);for(const i of items){const publicPort=Number(i.publicPort||i.port),internalPort=Number(i.internalPort||i.port);if(!(publicPort>0&&publicPort<65536))e.push(`${i.tag||i.id}: invalid public port`);if(!(internalPort>0&&internalPort<65536))e.push(`${i.tag||i.id}: invalid internal port`);if(seenInternal.has(internalPort))e.push(`Internal port conflict: ${internalPort}`);seenInternal.add(internalPort);if(httpish.has(i.transport)){if(i.security==='reality')e.push(`${i.tag||i.id}: REALITY cannot be path-routed through the HTTP gateway`);if(i.security==='tls')e.push(`${i.tag||i.id}: use gateway TLS termination with security=none for HTTP path routing`);const pathValue=i.path||(i.settings?.streamSettings?.wsSettings?.path)||(i.settings?.streamSettings?.xhttpSettings?.path)||'/';const key=`${publicPort}|${pathValue}`;if(pathSeen.has(key))e.push(`Gateway path conflict: public ${publicPort} ${pathValue}`);pathSeen.add(key)}else{const same=items.find(x=>x!==i&&Number(x.publicPort||x.port)===publicPort&&!httpish.has(x.transport));if(same)e.push(`Non-HTTP listener conflict on public port ${publicPort}`)}}return e}
function gatewayEntries(){const d=db();const httpish=new Set(['ws','xhttp','httpupgrade','http','grpc']);return d.inbounds.filter(i=>httpish.has(i.transport)).map(i=>({id:i.id,transport:i.transport,publicPort:Number(i.publicPort||i.port),path:i.path||i.settings?.streamSettings?.wsSettings?.path||i.settings?.streamSettings?.xhttpSettings?.path||'/',internalPort:Number(i.internalPort||i.port),host:i.host||''}))}
function writeNginxConfig(){const entries=gatewayEntries();let locations='';for(const x of entries){const p=x.path.startsWith('/')?x.path:'/'+x.path;const up=`http://127.0.0.1:${x.internalPort}`;if(x.transport==='grpc')locations+=`location = ${p} { grpc_pass ${up}; }\n`;else locations+=`location = ${p} { proxy_http_version 1.1; proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; proxy_set_header X-Forwarded-Proto $scheme; proxy_set_header Upgrade $http_upgrade; proxy_set_header Connection $connection_upgrade; proxy_buffering off; proxy_pass ${up}; }\n`; }const cfg=`worker_processes 1;\npid ${NGINX_PID};\nevents { worker_connections 4096; }\nhttp { map $http_upgrade $connection_upgrade { default upgrade; '' close; } access_log off; error_log ${DATA}/nginx-error.log warn; server { listen ${GATEWAY_PORT}; server_name _; ${locations || 'location = /__xray_health { return 200 "ok"; }'} } }\n`;fs.writeFileSync(NGINX_CFG,cfg)}
async function startNginx(){if(nginxProc)return nginxProc.pid;writeNginxConfig();if(!fs.existsSync(NGINX_BIN))throw new Error(`Nginx binary not found at ${NGINX_BIN}`);await new Promise((resolve,reject)=>{const p=spawn(NGINX_BIN,['-t','-c',NGINX_CFG]);let o='';p.stderr.on('data',d=>o+=d);p.on('error',reject);p.on('close',c=>c===0?resolve():reject(new Error(o||`nginx config test failed (${c})`))) });nginxProc=spawn(NGINX_BIN,['-c',NGINX_CFG,'-g','daemon off;'],{stdio:['ignore','pipe','pipe']});nginxProc.stdout.on('data',d=>pushLog('NGINX '+d));nginxProc.stderr.on('data',d=>pushLog('NGINX '+d));nginxProc.on('exit',()=>{nginxProc=null});return nginxProc.pid}
function stopNginx(){if(nginxProc){try{nginxProc.kill('SIGTERM')}catch{}nginxProc=null}}

function ensureDefaultInbound(){const d=db();if(d.inbounds.length)return;const u=crypto.randomUUID();d.inbounds.push({id:id(),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),protocol:'vless',transport:'ws',security:'none',listen:'127.0.0.1',port:INTERNAL_BASE,publicPort:443,path:'/vless',tag:'default-vless-ws',settings:{clients:[{id:u,email:'default'}],decryption:'none',streamSettings:{network:'ws',wsSettings:{path:'/vless',headers:{}}}}});saveDB(d);pushLog(`Created default VLESS/WS inbound for public 443 path /vless; internal ${INTERNAL_BASE}; client UUID=${u}`)}
async function validateRuntime(){const e=validateInbounds(db().inbounds);if(e.length)throw new Error(e.join(' | '));fs.writeFileSync(XRAY_CFG,JSON.stringify(runtimeConfig(),null,2));if(!fs.existsSync(XRAY_BIN))throw new Error(`Xray binary not found at ${XRAY_BIN}`);return new Promise((resolve,reject)=>{const p=spawn(XRAY_BIN,['run','-test','-config',XRAY_CFG]);let out='';p.stdout.on('data',d=>out+=d);p.stderr.on('data',d=>out+=d);p.on('error',reject);p.on('close',code=>code===0?resolve():reject(new Error(out||`Xray config test failed (${code})`)))})}
function stopXray(){if(xrayProc){try{xrayProc.kill('SIGTERM')}catch{}xrayProc=null;pushLog('Xray stopped')}}
async function startXray(force=false){if(xrayProc&&!force)return xrayProc.pid;await validateRuntime();stopXray();stopNginx();writeNginxConfig();xrayProc=spawn(XRAY_BIN,['run','-config',XRAY_CFG],{stdio:['ignore','pipe','pipe']});const proc=xrayProc;proc.stdout.on('data',d=>pushLog(d));proc.stderr.on('data',d=>pushLog(d));proc.on('error',e=>pushLog(`Xray process error: ${e.message}`));proc.on('exit',(code,sig)=>{pushLog(`Xray exited code=${code} signal=${sig||''}`);if(xrayProc===proc)xrayProc=null});await new Promise((resolve,reject)=>{let done=false;const t=setTimeout(()=>{if(!done){done=true;resolve()}},1200);const onExit=(code)=>{if(!done){done=true;clearTimeout(t);reject(new Error(`Xray exited during startup with code ${code}. See Runtime logs.`))}};proc.once('exit',onExit)});await startNginx();return proc.pid}
function pushLog(x){const s=String(x).trim();if(!s)return;xrayLog.push(s);if(xrayLog.length>300)xrayLog.shift()}
async function route(req,res,u){
if(u.pathname==='/login'&&req.method==='POST'){const b=await readBody(req),d=db();if(String(b.username)===d.auth.username&&hash(b.password)===d.auth.passwordHash){const token=crypto.randomBytes(32).toString('hex');sessions.set(token,{at:Date.now()});res.writeHead(200,{'Content-Type':'application/json','Set-Cookie':`xray_session=${token}; Path=/; HttpOnly; SameSite=Lax; Max-Age=86400`});return res.end(JSON.stringify({ok:true,username:d.auth.username}))}return json(res,401,{error:'نام کاربری یا رمز عبور نادرست است'})}
if(u.pathname==='/api/auth/me'){if(!auth(req))return json(res,401,{authenticated:false});const d=db();return json(res,200,{authenticated:true,username:d.auth.username})}
if(u.pathname==='/api/auth/logout'){const t=cookies(req).xray_session;sessions.delete(t);res.writeHead(200,{'Content-Type':'application/json','Set-Cookie':'xray_session=; Path=/; HttpOnly; Max-Age=0'});return res.end(JSON.stringify({ok:true}))}
if(u.pathname==='/api/auth/password'&&req.method==='POST'){if(!need(req,res))return;const b=await readBody(req),d=db();if(hash(b.currentPassword)!==d.auth.passwordHash)return json(res,400,{error:'رمز فعلی نادرست است'});if(!b.newUsername||!b.newPassword||String(b.newPassword).length<4)return json(res,400,{error:'نام کاربری و رمز جدید معتبر نیست'});d.auth={username:String(b.newUsername),passwordHash:hash(b.newPassword)};saveDB(d);return json(res,200,{ok:true})}
if(u.pathname==='/api/qr'){const d=u.searchParams.get('data');if(!d)return json(res,400,{error:'data required'});const svg=await QR.toString(d,{type:'svg',margin:1,width:300});res.writeHead(200,{'Content-Type':'image/svg+xml','Cache-Control':'no-store'});return res.end(svg)}
if(u.pathname==='/api/runtime-meta')return json(res,200,{publicDomain:process.env.RAILWAY_PUBLIC_DOMAIN||'',tcpProxyDomain:process.env.RAILWAY_TCP_PROXY_DOMAIN||'',tcpProxyPort:process.env.RAILWAY_TCP_PROXY_PORT||'',gatewayPort:GATEWAY_PORT,defaultPublicPort:443,allowedPorts:[80,443,2052,2053,2082,2083,2095,2096,8080,8081,8082,8083,8084,8085,8086,8087,8088,8089,8090,8443]});
if(u.pathname==='/api/health')return json(res,200,{ok:true,xray:!!xrayProc,nginx:!!nginxProc,inbounds:db().inbounds.length});
if(u.pathname==='/api/status'){if(!need(req,res))return;return json(res,200,{xray:{running:!!xrayProc,pid:xrayProc?.pid||null,binary:fs.existsSync(XRAY_BIN),config:fs.existsSync(XRAY_CFG)},nginx:{running:!!nginxProc,port:GATEWAY_PORT},railway:{publicDomain:process.env.RAILWAY_PUBLIC_DOMAIN||'',tcpProxyDomain:process.env.RAILWAY_TCP_PROXY_DOMAIN||'',tcpProxyPort:process.env.RAILWAY_TCP_PROXY_PORT||'',tcpApplicationPort:process.env.RAILWAY_TCP_APPLICATION_PORT||''},logs:xrayLog.slice(-100),inbounds:db().inbounds.length,configs:db().configs.length})}
if(u.pathname==='/api/config'){if(req.method!=='POST')return json(res,405,{error:'POST required'});const c=await readBody(req),e=validate(c);if(e.length)return json(res,400,{error:'Invalid configuration',fields:e});return json(res,200,{ok:true,...outputs(c)})}
if(u.pathname==='/api/saved'){if(!need(req,res))return;const d=db();if(req.method==='GET')return json(res,200,{items:d.configs});if(req.method==='POST'||req.method==='PUT'){const c=await readBody(req),e=validate(c);if(e.length)return json(res,400,{error:'Invalid',fields:e});if(req.method==='POST'){const item={id:id(),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),name:c.meta?.name||'Untitled',config:c,uri:uri(c)};item.subscriptionToken=crypto.randomBytes(12).toString('hex');d.configs.unshift(item);saveDB(d);return json(res,201,item)}const x=d.configs.find(a=>a.id===u.searchParams.get('id'));if(!x)return json(res,404,{error:'Not found'});Object.assign(x,{name:c.meta?.name||x.name,config:c,uri:uri(c),updatedAt:new Date().toISOString()});saveDB(d);return json(res,200,x)}if(req.method==='DELETE'){d.configs=d.configs.filter(a=>a.id!==u.searchParams.get('id'));saveDB(d);return json(res,200,{ok:true})}}
if(u.pathname==='/api/import'){if(!need(req,res))return;const body=await readBody(req);let x=body.json||body;try{if(typeof x==='string')x=JSON.parse(x)}catch{return json(res,400,{error:'Invalid JSON'})}const d=db();if(Array.isArray(x.configs)||Array.isArray(x.inbounds)){for(const a of (x.configs||[])){d.configs.unshift({...a,id:id(),subscriptionToken:crypto.randomBytes(12).toString('hex'),updatedAt:new Date().toISOString()})}for(const a of (x.inbounds||[])){d.inbounds.unshift({...a,id:id(),updatedAt:new Date().toISOString()})}const ce=validateInbounds(d.inbounds);if(ce.length)return json(res,409,{error:ce.join(' | ')});saveDB(d);return json(res,201,{ok:true,configsImported:(x.configs||[]).length,inboundsImported:(x.inbounds||[]).length})}return json(res,400,{error:'Unsupported import format'})}
if(u.pathname==='/api/export'){if(!need(req,res))return;const d=db();return json(res,200,{version:4,exportedAt:new Date().toISOString(),configs:d.configs,inbounds:d.inbounds})}
if(u.pathname==='/api/inbounds'){if(!need(req,res))return;const d=db();if(req.method==='GET')return json(res,200,{items:d.inbounds});if(req.method==='POST'||req.method==='PUT'){const i=await readBody(req);if(!i.protocol||!(Number(i.port||XRAY_DEFAULT_PORT)>0&&Number(i.port||XRAY_DEFAULT_PORT)<65536)||!['vless','vmess','trojan','shadowsocks'].includes(i.protocol))return json(res,400,{error:'protocol and valid port required'});if(!i.settings)i.settings={};if(!Array.isArray(i.settings.clients))i.settings.clients=[];i.publicPort=Number(i.publicPort||i.port||443);i.internalPort=Number(i.internalPort||i.port||INTERNAL_BASE+Math.floor(Math.random()*1000));if(i.transport==='ws'&&!i.path)i.path=i.settings.streamSettings?.wsSettings?.path||'/'+(i.tag||'xray').replace(/[^a-zA-Z0-9_-]/g,'');if(req.method==='POST'){i.id=id();i.createdAt=new Date().toISOString();d.inbounds.unshift(i)}else{const x=d.inbounds.find(a=>a.id===u.searchParams.get('id'));if(!x)return json(res,404,{error:'Not found'});Object.assign(x,i,{id:x.id,updatedAt:new Date().toISOString()})}const ce=validateInbounds(d.inbounds);if(ce.length)return json(res,409,{error:ce[0],code:'PORT_CONFLICT'});saveDB(d);if(xrayProc){try{await startXray(true)}catch(e){pushLog('RELOAD ERROR: '+e.message)}}return json(res,200,{ok:true,item:req.method==='POST'?i:d.inbounds.find(a=>a.id===i.id)})}if(req.method==='DELETE'){d.inbounds=d.inbounds.filter(a=>a.id!==u.searchParams.get('id'));saveDB(d);if(xrayProc){try{await startXray(true)}catch(e){pushLog('RELOAD ERROR: '+e.message)}}return json(res,200,{ok:true})}}
if(u.pathname==='/api/inbounds/runtime'){if(!need(req,res))return;const e=validateInbounds(db().inbounds);return json(res,e.length?409:200,e.length?{error:e.join(' | '),conflicts:e}:{ok:true,config:runtimeConfig()})}
if(u.pathname==='/api/xray/start'||u.pathname==='/api/xray/restart'){if(!need(req,res))return;try{const pid=await startXray(u.pathname.endsWith('/restart'));return json(res,200,{ok:true,pid})}catch(e){pushLog(`START ERROR: ${e.message}`);return json(res,500,{error:e.message,logs:xrayLog.slice(-20)})}}
if(u.pathname==='/api/xray/stop'){if(!need(req,res))return;stopXray();stopNginx();return json(res,200,{ok:true})}
if(u.pathname==='/sub/all'){const d=db(),items=d.configs;if(!items.length)return json(res,404,{error:'No configs'});const body=Buffer.from(items.map(x=>x.uri||uri(x.config)).join('\n')).toString('base64');res.writeHead(200,{'Content-Type':'text/plain; charset=utf-8','Cache-Control':'no-store'});return res.end(body)}
if(u.pathname.startsWith('/sub/')){const token=u.pathname.slice(5),d=db(),items=d.configs.filter(x=>x.id===token||x.subscriptionToken===token);if(!items.length)return json(res,404,{error:'Subscription not found'});const body=Buffer.from(items.map(x=>x.uri||uri(x.config)).join('\n')).toString('base64');res.writeHead(200,{'Content-Type':'text/plain; charset=utf-8','Cache-Control':'no-store'});return res.end(body)}return false}
init();const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,`http://${req.headers.host||'localhost'}`);const handled=await route(req,res,u);if(handled!==false)return;let f=path.normalize(u.pathname==='/'?'/index.html':u.pathname).replace(/^\.\.(\/|\\)/,'');const full=path.join(PUBLIC,f);if(!full.startsWith(PUBLIC))return json(res,403,{error:'Forbidden'});fs.readFile(full,(e,d)=>{if(e){res.writeHead(404);return res.end('Not found')}res.writeHead(200,{'Content-Type':MIME[path.extname(full)]||'application/octet-stream'});res.end(d)})}catch(e){json(res,500,{error:e.message})}});server.listen(PORT,'0.0.0.0',async()=>{console.log(`Panel listening on ${PORT}`);try{ensureDefaultInbound();if(String(process.env.XRAY_AUTOSTART||'true')==='true')await startXray()}catch(e){pushLog(`AUTOSTART ERROR: ${e.message}`)}});process.on('SIGTERM',()=>{stopXray();stopNginx();process.exit(0)});
